document.write('<div data-role="page" id="testpage">');
document.write('<div data-role="header">');
document.write('<h1>BitMac</h1>');
document.write('<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-icon-back ui-btn-icon-left ui-btn-icon-notext">Back</a></div>');
document.write('<div class="ui-content" role="main">');
document.write('<a href="#panel-push" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-mini ui-btn-icon-left ui-icon-bars">Push</a>');
document.write('<form class="ui-mini">');
document.write('<div class="ui-field-contain" id="theme-selector">');
document.write('<fieldset data-role="controlgroup" data-type="horizontal">');
document.write('<label for="a">Light</label>');
document.write('<input type="radio" name="theme" id="a" checked>');
document.write('<label for="b">Black</label>');
document.write('<input type="radio" name="theme" id="b"></fieldset></div></form>');
document.write('<p>The Era of Digital Payment!</p>');
document.write('<table width="20%" id="rcorners1">');
document.write('<tr><td colspan="2">');
document.write('<div class="coinmarketcap-currency-widget" data-currencyid="1" data-base="HKD" data-secondary="USD"></div>');
document.write('</td></tr><tr>');
document.write('<td align="center"><p id="rcorners3"></p><p id="rcorners4"></p></td>');
document.write('<td id="rcorners2"></td>');
document.write('</tr></table></div>');
document.write('<div data-role="panel" id="panel-push" data-display="push">');
document.write('<ul data-role="listview">');
document.write('<li data-icon="delete"><a href="#" data-rel="close">Close</a></li>');
document.write('<li data-icon="home"><a href="about.html" data-rel="dialog" data-transition="flip">About BitMac</a></li>');
document.write('<li data-icon="location"><a href="location.html" data-rel="dialog" data-transition="flip">Locate our Machine</a></li>');
document.write('</ul></div></div>');